// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hlllpkkiwvpfdhopgxny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhsbGxwa2tpd3ZwZmRob3BneG55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODkyNjgsImV4cCI6MjA2Mzc2NTI2OH0.EwZNCo8MiZKNbkevBhvuJKx60QW2RA--yKHf4T3BQI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);